### ISSUE TITLE
Exception EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by AlexDeyth686** [thelivingdiamond/Chairloader#135]
Hello, just updated to 1.2.3 and crash at start.

Version 1.2.2 work fine.

I upload log and dmp file like requested by log file.

Thanks

[ChairManager-Crash-2024-06-30-13-26-25.dmp](https://github.com/user-attachments/files/16044168/ChairManager-Crash-2024-06-30-13-26-25.dmp)
[ChairManager-Crash-2024-06-30-13-26-25.txt](https://github.com/user-attachments/files/16044169/ChairManager-Crash-2024-06-30-13-26-25.txt)

**Comment by tmp64** [comment]
Seems like Microsoft changed something in a recent compiler update. Install the latest MSVC++ Runtime from [here](https://aka.ms/vs/17/release/vc_redist.x64.exe)

**Comment by bakanisan** [comment]
> Seems like Microsoft changed something in a recent compiler update. Install the latest MSVC++ Runtime from [here](https://aka.ms/vs/17/release/vc_redist.x64.exe)

Thanks I successfully launched it.
