### ISSUE TITLE
Mod Manager Not Recognizing GOG Version of the Game

### ISSUE THREAD

**Issue by GeQi** [thelivingdiamond/Chairloader#49]
The mod manager complains about unknown version when pointed to GOG version of the game.
This happens under SteamOS on Steam Deck using [proton-GE](https://github.com/GloriousEggroll/proton-ge-custom) to launch the mod manager via game mode.

**Comment by tmp64** [comment]
I added support for it. You can get the automatic build on [GitHub Actions](https://github.com/thelivingdiamond/Chairloader/actions/runs/4624802581) once it finishes building

**Comment by GeQi** [comment]
@tmp64 Thanks! Can confirm the new build works now.
However I do get a new error #50.
