### ISSUE TITLE
Unknown Exception While Deploying Touch-up Mod

### ISSUE THREAD

**Issue by GeQi** [thelivingdiamond/Chairloader#50]
While deploying the touch-up mod I get the following fatal error.
![Screenshot_20230406_021815](https://user-images.githubusercontent.com/4011632/230318468-e691c70a-fa4c-42b6-9383-0080655167aa.png)

Attached is the log from mod manager.
[ChairManager.log](https://github.com/thelivingdiamond/Chairloader/files/11167978/ChairManager.log)

This happens under SteamOS on Steam Deck using [proton-GE](https://github.com/GloriousEggroll/proton-ge-custom) to launch the mod manager.

**Comment by GeQi** [comment]
Multiple texts do not show up correctly afterwards, so the installation did not finish successfully.
![20230406024331_1](https://user-images.githubusercontent.com/4011632/230327821-77f1f7cf-bc04-49d8-b0df-932b71b0fbd4.jpg)
![20230406024301_1](https://user-images.githubusercontent.com/4011632/230327831-0c46e35b-ec6e-4334-b7e4-dd3017d1b697.jpg)
![20230406024246_1](https://user-images.githubusercontent.com/4011632/230327838-3d6d0809-9253-4f9b-bc92-fe198a8ff627.jpg)

**Comment by tmp64** [comment]
I added better logging for unhandled exceptions in [this version](https://github.com/thelivingdiamond/Chairloader/actions/runs/4629877492). Send ChairManagerError.log once the error happens

**Comment by GeQi** [comment]
@tmp64 Here's the error log, thanks!
[ChairManagerError.log](https://github.com/thelivingdiamond/Chairloader/files/11174663/ChairManagerError.log)

**Comment by thelivingdiamond** [comment]
Hello, can you please include the entire log? It's hard to tell what's going on with just the exception. Thanks

**Comment by tmp64** [comment]
The error handler I added yesterday turned out to be just as useful as the "Unknown exception" message.

[This one](https://github.com/thelivingdiamond/Chairloader/actions/runs/4637851406) should have proper crash handling. Make sure to include `ChairManager.log`, `ChairManager-Crash-???.txt` and `ChairManager-Crash-???.dmp` next time it crashes

**Comment by GeQi** [comment]
@tmp64 @thelivingdiamond Here's the log and dump.
[ChairManager.log](https://github.com/thelivingdiamond/Chairloader/files/11179165/ChairManager.log)
[ChairManager-Crash-2023-04-07-07-18-37.txt](https://github.com/thelivingdiamond/Chairloader/files/11179166/ChairManager-Crash-2023-04-07-07-18-37.txt)
[ChairManager-Crash-2023-04-07-07-18-37.dmp.zip](https://github.com/thelivingdiamond/Chairloader/files/11179178/ChairManager-Crash-2023-04-07-07-18-37.dmp.zip)

**Comment by tmp64** [comment]
@thelivingdiamond The exception is thrown here, during the `get()` call. I don't know what causes the exception in the task though.
https://github.com/thelivingdiamond/Chairloader/blob/bd6566feb47d56afc78f049f7c0a4a95f5cbdd17/ChairManager/ChairManager.cpp#L2428-L2434

**Comment by thelivingdiamond** [comment]
@tmp64 looking at the log it looks like it gets through merging and probably fails at packing the executables. Do we know if the proton-ge layer works ok with the 7za.exe process pool?

**Comment by tmp64** [comment]
It should. I tested with Wine yesterday, there were no errors.

**Comment by tmp64** [comment]
ChairManager works fine with proton-GE on my laptop. @GeQi how do you launch the .exe?

**Comment by GeQi** [comment]
@tmp64 I launched it by adding `ChairManager.exe` as a non-steam game to steam client and chossing proton-GE as complatibility tool.

**Comment by tmp64** [comment]
No longer happens in new ChairManager. Chairloader DLL requires a custom envvar (more in #51)
