### ISSUE TITLE
cant access trainer

### ISSUE THREAD

**Issue by BrainlessKiwi** [thelivingdiamond/Chairloader#59]
when I launch prey via chairloader with mods the trainer doesn't show
![image_2023-06-05_113735202](https://github.com/thelivingdiamond/Chairloader/assets/135559734/1c39d520-b596-4e21-8065-1ddb33598083)

**Comment by tmp64** [comment]
Trainer needs to be explicitly enabled using this checkbox in the options menu or using `-trainer` [command line option](https://github.com/thelivingdiamond/Chairloader/wiki/Command-Line-Options).
![image](https://github.com/thelivingdiamond/Chairloader/assets/20199236/63ebec38-6499-4d18-9f6f-cb607019aeb5)
