### ISSUE TITLE
GOG Version Not Recognized

### ISSUE THREAD

**Issue by Chromodyne** [thelivingdiamond/Chairloader#69]
I am attempted to use Chair Manager on the GOG version of the game; however, it is saying that the version is unknown when the conversion prompt appears. I saw a closed Issue saying that this problem was resolved but I'm still experiencing it.

Thanks!

**Comment by tmp64** [comment]
This version hasn't been released yet. You can download a dev build [here](https://github.com/thelivingdiamond/Chairloader/actions?query=branch%3Amain). Select the top (newest) build and download `Chairloader-XXXXXX-RelWithDebInfo` from Artifacts.
