### ISSUE TITLE
`g_detachedCameraMoveSpeed` command doesn't work

### ISSUE THREAD

**Issue by originalnicodr** [thelivingdiamond/Chairloader#92]
Given that the camera speed is way faster than I needed it I wanted to use this command to tune it down, but it seems that it doesn't do anything. I tried to use a joystick as an alternative to having more granular control over the camera, but its velocity was still too high.

I don't expect anyone to try to reimplement commands if they were stripped from the release exe, but I thought I could at least point it out. Feel free to mark it as "won't fix" if you are not interested in doing something about it.

In any case, thank you for the hard work on this project!

**Comment by thelivingdiamond** [comment]
Are you using the in engine freecam (F2) or the chairloader editor freecam (F4 when the editor is enabled)?

The freecam move speed cvar only affects the editor freecam speed.

**Comment by originalnicodr** [comment]
I am using the engines' freecam, since I need to use commands like `cl_fov` to modify the fov, and they only affect the "gameplay" camera.

Having said that, I just took a look and found `ed_ViewFov`, `ed_ViewMaxSpeed`, and `ed_ViewMinSpeed`. So I can try to use the editor camera instead of the engine camera, so thanks for pointing the editor out!

For added context, I like to [use freecams to take screenshots](https://originalnicodr.github.io/virtual-photography/) in games and [document the process when possible](https://framedsc.com/), so being able to move the camera with more precision (aka slower) , and also being able to edit the fov is very important for my use case. But like I said, feel free to ignore this if you don't feel like it's worth putting the work into that.

**Comment by thelivingdiamond** [comment]
We tried to fix the freecam speed in the past, and it was easier to just add a new freecam with more features overall.

**Comment by originalnicodr** [comment]
Oh, then don't mind me! I will just use the editor's freecam then.

Sorry for bothering you, and thanks again for your and the team's time on this!
